---
- name: Ensure outdir exists
  file: dest={{ image_outdir }} state=directory

- name: Look for image files
  stat:
    path: "{{ image_outdir }}/{{ distro }}-{{ release}}.{{ item }}"
  register: st
  with_items: "{{ formats }}"

- name: Build disk image
  shell: disk-image-create -n -x --no-tmpfs -t {{ formats|join(',') }} -o {{ image_outdir}}/{{ distro }}-{{ release }} {{ distro }}-minimal vm {{ elements|default([])|join(' ') }}
  args:
    chdir: "{{ image_tmpdir }}"
  environment:
    ELEMENTS_PATH: "{{ elements_path|default(omit)|join(':') }}"
    QEMU_IMG_OPTIONS: "{{ qemu_image_options|default(omit) }}"
    DIB_RELEASE: "{{ release }}"
  register: image_create
  when: " {{ st.results|map(attribute='stat')|list()|selectattr('exists', 'sameas', false)|list()|length() > 0 }} "
