---
- name: Make basename
  set_fact:
      imagename: "{{ distro }}-{{ release }}"
- name: Look for image files
  stat:
    path: "{{ image_outdir }}/{{ imagename }}.{{ item }}"
  register: st
  with_items: "{{ clouds|map(attribute='format')|list() }}"
- name: Build disk image
  shell: "disk-image-create -n -x --no-tmpfs -t {{ clouds|map(attribute='format')|join(',') }} -o {{ image_outdir}}/{{ imagename }} {{ distro }}-minimal vm {{ elements|default('') }}"
  args:
    chdir: "{{ image_tmpdir }}"
  environment:
    ELEMENTS_PATH: "{{ elements_path|default(omit) }}"
    QEMU_IMG_OPTIONS: "{{ qemu_image_options|default(omit) }}"
    DIB_RELEASE: "{{ release }}"
  register: image_create
  when: " {{ st.results|map(attribute='stat')|list()|selectattr('exists', 'sameas', false)|list()|length() > 0 }} "
- name: Upload the image
  os_image:
    cloud: "{{ item.0.name }}"
    region_name: "{{ item.1 }}"
    name: "{{ prefix|default }}-{{ imagename }}"
    wait: yes
    timeout: 3600
    filename: "{{ image_outdir }}/{{ imagename }}.{{ item.0.format }}"
    properties: "{{ item.0.properties|default(omit) }}"
    container_format: "{{ item.0.container_format|default(omit) }}"
    disk_format: "{{ item.0.format }}"
  with_subelements:
  - clouds
  - regions
